# Generated by Django 3.0.5 on 2020-04-12 07:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer_Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recipient_Name', models.CharField(max_length=110)),
                ('amount', models.FloatField()),
                ('account_no', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999999999999)])),
                ('IFSC', models.CharField(max_length=110)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('current_user', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'TRANSFEr_MONEY',
                'db_table': 'transfer_money',
                'managed': True,
            },
        ),
    ]
