# Generated by Django 3.0.5 on 2020-04-13 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_transfer_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer_money',
            name='account_no',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(99999999999999999)]),
        ),
    ]
