# Generated by Django 3.0.5 on 2020-04-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200413_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer_money',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
